### ISSUE TITLE
No datapoints an map

### ISSUE THREAD

**Issue by TheHades** [rji/icmp-echo-scan-viz#1]
Hello,
i dont see any datapoints on my map.
The datapoints.js contains data and i´ve also added my Google Maps API-Key.

Any suggestions?

Thanks, :)

**Comment by rji** [comment]
By default, the datapoints only have a 1px radius on the map, because we're expecting millions of them. If you're using the example data, it's simply not enough to cover the entire map _and_ be able to see it.

If you want to make sure it's working, you could set `radius: 10` or something in map.html. I just did this with the example data that I've included in this repo, and it works fine.
